version: '3'
services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
    # simply copy all the files inside frontend into container /app directory
      - /home/node/app/node_modules
      - ./frontend:/home/node/app
